# Configuración de HMPlugin (Permadeath Reborn)
# Versión 1.0.0

# Prefijo que se mostrará en los mensajes del chat
prefix: "<gradient:red:dark_red>PermaDeath</gradient> <gray>» "

# Configuración de mensajes
messages:
  death: "<red>El jugador <yellow>%player% <red>ha muerto y ha sido PERMABANEADO."
  storm_start: "<dark_red>¡Ha comenzado el Death Train!"

# Opciones de juego
game:
  # Día actual del HMPlugin (Permadeath)
  day: 1
  # Fecha de inicio del HMPlugin (Permadeath) (formato: YYYY-MM-DD, se configura automáticamente)
  start_date: ""
  # Activar el ban al morir
  ban_enabled: true

discord_api:
  base_url: "https://bot.warevision.net"
  api_key: ""
  heartbeat_interval_secs: 15

# Webhook para notificar el estado del servidor (abierto/cerrado)
server_status_webhook: "https://n8n.warevision.net/webhook-test/a3062da4-c838-48f8-b355-2a82065a798f"